#!/bin/bash
# Build script for UTF-8 wasm module
# Requires: binaryen (brew install binaryen)

set -e

cd "$(dirname "$0")"

echo "Compiling utf8.wat -> utf8.wasm..."
wasm-as utf8.wat -o utf8.wasm --enable-reference-types --enable-gc --enable-strings

echo "Generating base64 TypeScript module..."
cat > ../src/utils/utf8-wasm-binary.ts << 'HEADER'
// Auto-generated by wasm/build.sh - do not edit manually
// Source: wasm/utf8.wat

HEADER

echo -n "export const wasmBinary = \"" >> ../src/utils/utf8-wasm-binary.ts
base64 -i utf8.wasm | tr -d '\n' >> ../src/utils/utf8-wasm-binary.ts
echo "\";" >> ../src/utils/utf8-wasm-binary.ts

echo "Done! Generated:"
echo "  - wasm/utf8.wasm ($(wc -c < utf8.wasm | tr -d ' ') bytes)"
echo "  - src/utils/utf8-wasm-binary.ts ($(wc -c < ../src/utils/utf8-wasm-binary.ts | tr -d ' ') bytes)"
