// Build script for UTF-8 wasm module
// Invoked by `npm run build:wasm`

/* eslint-disable no-console */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import binaryen from "binaryen";
import binaryenMetadata from "binaryen/package.json" with { type: "json" };


const dirname = path.dirname(fileURLToPath(import.meta.url));

const watPath = path.join(dirname, "utf8.wat");
const wasmPath = path.join(dirname, "utf8.wasm");
const tsOutputPath = path.join(dirname, "..", "src", "utils", "utf8-wasm-binary.ts");

console.log(`Compiling utf8.wat -> utf8.wasm with Binaryen v${binaryenMetadata.version}...`);

// Read WAT source
const watSource = fs.readFileSync(watPath, "utf-8");

// Parse WAT to module
const mod = binaryen.parseText(watSource);

// Enable required features
mod.setFeatures(binaryen.Features.ReferenceTypes | binaryen.Features.GC | binaryen.Features.Strings);

// Optimize (equivalent to wasm-opt -O4)
mod.optimize();

// Emit binary
const wasmBinary = mod.emitBinary();

// Write wasm file
fs.writeFileSync(wasmPath, wasmBinary);

console.log("Generating base64 TypeScript module...");

// Convert to base64 with line breaks (like base64 -b 78)
const base64 = Buffer.from(wasmBinary).toString("base64");
const base64WithLineBreaks = base64.match(/.{1,78}/g)?.join("\n") ?? base64;

// Generate TypeScript file
const tsContent = `// Auto-generated by wasm/build.mts - DO NOT EDIT MANUALLY
// Source: wasm/utf8.wat

export const wasmBinary = \`
${base64WithLineBreaks}
\`;
`;

fs.writeFileSync(tsOutputPath, tsContent);

// Clean up
mod.dispose();

console.log("Done! Generated:");
console.log(`  - wasm/utf8.wasm (${wasmBinary.length} bytes)`);
console.log(`  - src/utils/utf8-wasm-binary.ts (${Buffer.byteLength(tsContent)} bytes)`);
