#!/bin/bash
# Build script for UTF-8 wasm module
# Requires: binaryen (brew install binaryen)

set -e

cd "$(dirname "$0")"

echo "Compiling utf8.wat -> utf8.wasm..."
wasm-as utf8.wat -o utf8.wasm --enable-reference-types --enable-gc --enable-strings
wasm-opt --enable-gc --enable-strings --enable-reference-types -O4 utf8.wasm -o tmp.wasm
mv tmp.wasm utf8.wasm

echo "Generating base64 TypeScript module..."

{
  echo "// Auto-generated by wasm/build.sh - DO NOT EDIT MANUALLY"
  echo "// Source: wasm/utf8.wat"
  echo ""
  echo "export const wasmBinary = \`"
  base64 -b 78 -i utf8.wasm
  echo "\`;"
} > ../src/utils/utf8-wasm-binary.ts

echo "Done! Generated:"
echo "  - wasm/utf8.wasm ($(wc -c < utf8.wasm | tr -d ' ') bytes)"
echo "  - src/utils/utf8-wasm-binary.ts ($(wc -c < ../src/utils/utf8-wasm-binary.ts | tr -d ' ') bytes)"
